uploads = []
generated = []

[[outputs]]
id = "q_QKrm-fvsrcuTtP3NC3h"
uri = "file://android/app/build/outputs/apk/debug/ShopLedger-debug-v1.0.2.zip"
type = "unspecified"
title = "ShopLedger Debug APK v1.0.2 (install with adb or sideload)"
